2022-12-15 12:32:03,863 INFO    StreamThr :19067 [internal.py:wandb_internal():88] W&B internal server running at pid: 19067, started at: 2022-12-15 12:32:03.860710
2022-12-15 12:32:03,948 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: status
2022-12-15 12:32:03,949 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: status
2022-12-15 12:32:03,951 INFO    WriterThread:19067 [datastore.py:open_for_write():75] open: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/run-2j62uv9h.wandb
2022-12-15 12:32:03,951 DEBUG   SenderThread:19067 [sender.py:send():303] send: header
2022-12-15 12:32:03,952 DEBUG   SenderThread:19067 [sender.py:send():303] send: run
2022-12-15 12:32:03,956 INFO    SenderThread:19067 [sender.py:_maybe_setup_resume():593] checking resume status for None/U-Net/2j62uv9h
2022-12-15 12:32:05,659 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: check_version
2022-12-15 12:32:05,676 INFO    SenderThread:19067 [dir_watcher.py:__init__():216] watching files in: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files
2022-12-15 12:32:05,676 INFO    SenderThread:19067 [sender.py:_start_run_threads():928] run started: 2j62uv9h with start time 1671078723.859062
2022-12-15 12:32:05,677 DEBUG   SenderThread:19067 [sender.py:send():303] send: summary
2022-12-15 12:32:05,677 INFO    SenderThread:19067 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-12-15 12:32:05,678 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: check_version
2022-12-15 12:32:06,236 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: run_start
2022-12-15 12:32:06,247 DEBUG   HandlerThread:19067 [system_info.py:__init__():31] System info init
2022-12-15 12:32:06,248 DEBUG   HandlerThread:19067 [system_info.py:__init__():46] System info init done
2022-12-15 12:32:06,248 INFO    HandlerThread:19067 [system_monitor.py:start():150] Starting system monitor
2022-12-15 12:32:06,248 INFO    SystemMonitor:19067 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-12-15 12:32:06,249 INFO    HandlerThread:19067 [system_monitor.py:probe():168] Collecting system info
2022-12-15 12:32:06,250 INFO    SystemMonitor:19067 [interfaces.py:start():168] Started cpu
2022-12-15 12:32:06,252 INFO    SystemMonitor:19067 [interfaces.py:start():168] Started disk
2022-12-15 12:32:06,254 INFO    SystemMonitor:19067 [interfaces.py:start():168] Started gpu
2022-12-15 12:32:06,255 INFO    SystemMonitor:19067 [interfaces.py:start():168] Started memory
2022-12-15 12:32:06,257 INFO    SystemMonitor:19067 [interfaces.py:start():168] Started network
2022-12-15 12:32:06,281 DEBUG   HandlerThread:19067 [system_info.py:probe():195] Probing system
2022-12-15 12:32:06,294 DEBUG   HandlerThread:19067 [system_info.py:_probe_git():180] Probing git
2022-12-15 12:32:06,326 DEBUG   HandlerThread:19067 [system_info.py:_probe_git():188] Probing git done
2022-12-15 12:32:06,326 DEBUG   HandlerThread:19067 [system_info.py:probe():241] Probing system done
2022-12-15 12:32:06,327 DEBUG   HandlerThread:19067 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-56-generic-x86_64-with-glibc2.29', 'python': '3.8.10', 'heartbeatAt': '2022-12-15T04:32:06.281445', 'startedAt': '2022-12-15T04:32:03.816293', 'docker': None, 'cuda': '11.0.207', 'args': (), 'state': 'running', 'program': '/media/breeze/dev/Mf_Cls/train.py', 'codePath': 'train.py', 'git': {'remote': 'https://github.com/Breezewrf/Mf_Cls.git', 'commit': '4bb7823ab295acc2520530d0b895d392abdfec47'}, 'email': '578450426@qq.com', 'root': '/media/breeze/dev/Mf_Cls', 'host': 'breeze-Ubuntu', 'username': 'breeze', 'executable': '/media/breeze/dev/Mf_Cls/venv/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2124.19, 'min': 400.0, 'max': 3400.0}, 'cpu_freq_per_core': [{'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}, {'current': 2329.083, 'min': 400.0, 'max': 3400.0}, {'current': 1800.0, 'min': 400.0, 'max': 3400.0}], 'disk': {'total': 70.03250503540039, 'used': 46.26530456542969}, 'gpu': 'NVIDIA GeForce MX150', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce MX150', 'memory_total': 2147483648}], 'memory': {'total': 15.507335662841797}}
2022-12-15 12:32:06,327 INFO    HandlerThread:19067 [system_monitor.py:probe():178] Finished collecting system info
2022-12-15 12:32:06,327 INFO    HandlerThread:19067 [system_monitor.py:probe():181] Publishing system info
2022-12-15 12:32:06,327 DEBUG   HandlerThread:19067 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-12-15 12:32:06,328 DEBUG   HandlerThread:19067 [system_info.py:_save_pip():67] Saving pip packages done
2022-12-15 12:32:06,331 INFO    HandlerThread:19067 [system_monitor.py:probe():183] Finished publishing system info
2022-12-15 12:32:06,344 DEBUG   SenderThread:19067 [sender.py:send():303] send: files
2022-12-15 12:32:06,345 INFO    SenderThread:19067 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-12-15 12:32:06,358 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:32:06,360 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:32:06,694 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_created():275] file/dir created: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/wandb-metadata.json
2022-12-15 12:32:06,696 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_created():275] file/dir created: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/wandb-summary.json
2022-12-15 12:32:06,698 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_created():275] file/dir created: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/requirements.txt
2022-12-15 12:32:06,770 DEBUG   SenderThread:19067 [sender.py:send():303] send: telemetry
2022-12-15 12:32:06,785 DEBUG   SenderThread:19067 [sender.py:send():303] send: config
2022-12-15 12:32:07,693 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_created():275] file/dir created: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/output.log
2022-12-15 12:32:07,712 INFO    Thread-20 :19067 [upload_job.py:push():143] Uploaded file /tmp/tmpb96pokvewandb/11h8sphc-wandb-metadata.json
2022-12-15 12:32:09,701 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_modified():292] file/dir modified: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/output.log
2022-12-15 12:32:21,796 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:32:21,798 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:32:36,812 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_modified():292] file/dir modified: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/config.yaml
2022-12-15 12:32:37,501 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:32:37,503 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:32:53,172 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:32:53,173 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:33:06,257 DEBUG   SystemMonitor:19067 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-12-15 12:33:06,263 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:33:08,825 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:33:08,826 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:33:24,459 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:33:24,460 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:33:36,267 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:33:40,007 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:33:40,009 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:33:49,121 INFO    Thread-17 :19067 [dir_watcher.py:_on_file_modified():292] file/dir modified: /media/breeze/dev/Mf_Cls/wandb/run-20221215_123203-2j62uv9h/files/output.log
2022-12-15 12:33:55,654 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:33:55,656 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:34:06,270 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:34:11,110 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:34:11,111 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:34:26,661 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:34:26,663 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:34:36,273 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:34:42,029 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:34:42,031 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:34:57,662 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:34:57,664 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:35:06,276 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:35:13,398 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:35:13,399 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:35:29,148 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:35:29,149 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:35:36,280 DEBUG   SenderThread:19067 [sender.py:send():303] send: stats
2022-12-15 12:35:45,210 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:35:45,212 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:36:00,866 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:36:00,867 DEBUG   SenderThread:19067 [sender.py:send_request():317] send_request: stop_status
2022-12-15 12:36:20,867 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:36:33,788 ERROR   SenderThread:19067 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fbd544d34c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544d34c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 210, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/media/breeze/dev/Mf_Cls/venv/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544d34c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-12-15 12:36:40,869 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:37:00,871 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:37:20,872 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:37:40,874 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:38:00,875 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:38:20,877 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:38:40,879 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:39:00,881 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:39:20,882 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:39:40,884 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:40:00,885 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:40:20,887 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:40:40,888 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:41:00,890 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:41:20,891 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:41:40,893 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:42:00,894 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:42:20,896 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:42:40,897 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:43:00,899 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:43:20,901 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:43:40,902 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:44:00,904 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:44:20,905 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:44:40,906 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:45:00,907 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:45:20,909 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:45:40,910 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:46:00,912 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:46:20,914 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:46:40,915 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:47:00,917 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:47:20,919 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:47:40,920 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:48:00,922 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:48:20,923 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:48:40,924 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:49:00,926 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:49:20,928 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:49:40,929 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:50:00,931 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:50:20,932 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:50:40,934 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:51:00,935 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:51:20,936 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:51:40,938 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:52:00,940 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:52:20,941 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:52:40,942 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:52:57,193 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', OSError(101, 'Network is unreachable')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:52:59,516 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:53:00,944 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:53:04,482 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:53:13,836 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394d60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:53:20,945 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:53:33,693 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:53:40,947 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:54:00,948 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:54:09,870 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:54:20,950 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:54:40,952 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:55:00,954 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:55:20,955 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:55:27,070 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544dcaf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:55:40,957 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:56:00,958 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:56:20,960 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:56:40,961 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:57:00,962 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:57:20,964 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:57:40,965 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:57:56,523 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544e04c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 12:58:00,967 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:58:20,968 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:58:40,968 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:59:00,971 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:59:20,972 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 12:59:40,974 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:00:00,975 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:00:20,977 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:00:40,979 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:01:00,981 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:01:20,982 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:01:40,984 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:02:00,985 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:02:20,987 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:02:40,989 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:03:00,990 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:03:03,079 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544e0df0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:03:20,992 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:03:40,993 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:04:00,995 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:04:20,997 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:04:40,998 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:05:00,999 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:05:21,001 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:05:41,003 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:06:01,005 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:06:21,006 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:06:41,008 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:07:01,009 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:07:21,011 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:07:41,012 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:08:01,014 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:08:16,796 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544e04c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:08:21,016 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:08:41,017 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:09:01,018 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:09:21,020 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:09:41,021 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:10:01,023 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:10:21,024 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:10:41,026 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:11:01,027 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:11:21,029 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:11:41,030 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:12:01,032 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:12:21,034 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:12:41,036 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:13:01,037 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:13:21,038 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:13:21,683 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394640>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:13:41,040 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:14:01,042 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:14:21,043 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:14:41,045 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:15:01,047 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:15:21,048 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:15:41,050 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:16:01,051 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:16:21,053 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:16:41,054 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:17:01,054 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:17:21,057 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:17:41,058 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:18:01,059 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:18:21,061 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:18:41,062 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:19:01,064 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:19:21,065 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:19:28,245 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544e2370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:19:41,067 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:20:01,068 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:20:21,070 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:20:41,071 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:21:01,073 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:21:21,075 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:21:41,077 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:22:01,078 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:22:21,080 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:22:41,081 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:23:01,083 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:23:21,084 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:23:41,085 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:24:01,087 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:24:21,088 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:24:29,276 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544e23a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:24:41,090 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:25:01,091 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:25:21,093 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:25:41,094 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:26:01,096 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:26:21,097 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:26:41,099 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:27:01,100 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:27:21,102 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:27:41,103 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:28:01,105 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:28:21,107 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:28:41,109 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:29:01,110 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:29:21,111 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:29:41,112 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:30:01,114 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:30:21,116 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:30:41,118 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:30:43,947 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544dc130>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:31:01,119 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:31:21,121 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:31:41,122 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:32:01,123 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:32:21,125 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:32:41,126 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:33:01,128 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:33:21,129 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:33:41,131 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:34:01,132 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:34:21,134 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:34:41,136 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:35:01,137 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:35:21,138 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:35:41,141 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:35:53,650 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd544dc0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:36:01,142 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:36:21,143 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:36:41,145 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:37:01,147 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:37:21,148 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:37:41,149 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:38:01,151 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:38:21,152 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:38:41,152 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:39:01,155 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:39:21,157 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:39:41,157 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:40:01,159 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:40:21,161 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:40:41,161 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:41:01,163 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:41:21,165 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:41:23,476 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:41:41,167 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:42:01,168 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:42:21,170 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:42:41,171 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:43:01,173 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:43:21,174 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:43:41,176 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:44:01,177 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:44:21,180 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:44:41,180 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:45:01,182 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:45:21,183 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:45:41,184 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:46:01,186 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:46:21,187 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:46:41,189 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:47:01,190 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:47:21,192 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:47:28,728 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:47:41,193 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:48:01,195 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:48:21,197 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:48:41,198 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:49:01,199 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:49:21,201 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:49:41,203 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:50:01,204 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:50:21,206 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:50:41,207 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:51:01,208 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:51:21,210 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:51:41,211 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:52:01,213 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:52:21,214 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:52:41,216 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:53:01,218 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:53:21,219 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:53:29,191 WARNING FileStreamThread:19067 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/anony-mouse-460985/U-Net/2j62uv9h/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd54394a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbd54615700>>, args: ('https://api.wandb.ai/files/anony-mouse-460985/U-Net/2j62uv9h/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2022-12-15 13:53:41,221 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:54:01,222 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
2022-12-15 13:54:21,223 DEBUG   HandlerThread:19067 [handler.py:handle_request():139] handle_request: stop_status
